listening-port=3478
fingerprint
lt-cred-mech
realm=sc.bjedu.pro
server-name=turn.sc.bjedu.pro
external-ip=192.168.1.100
min-port=49152
max-port=65535
user=shanchuan:j080mbaeIL7PlBBtQm7bedcc
no-multicast-peers
no-cli
log-file=stdout
